version: "3.8"
services:
  boardgamebkkwebsite:
    build: .
    container_name: boardgamebkkwebsite
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "3m"
        max-file: "3"
    ports:
      - 3000
    healthcheck:
      test: curl --fail -s http://localhost:3000/ || exit 1
      start_period: 3s
      interval: 3s
      timeout: 3s
      retries: 3
    networks:
      - caddy

networks:
  caddy:
    external: true
